/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef proto_CONSTANTS_H
#define proto_CONSTANTS_H

#include "proto_types.h"

namespace tw { namespace maple { namespace generated {

class protoConstants {
 public:
  protoConstants();

};

extern const protoConstants g_proto_constants;

}}} // namespace

#endif
