/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "proto_constants.h"

namespace tw { namespace maple { namespace generated {

const protoConstants g_proto_constants;

protoConstants::protoConstants() {
}

}}} // namespace

