/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef proto_TYPES_H
#define proto_TYPES_H

#include <Thrift.h>
#include <TApplicationException.h>
#include <protocol/TProtocol.h>
#include <transport/TTransport.h>



namespace tw { namespace maple { namespace generated {

struct DataFormat {
  enum type {
    TEXT = 0,
    IMAGE = 1,
    AUDIO = 2,
    VIDEO = 3
  };
};

extern const std::map<int, const char*> _DataFormat_VALUES_TO_NAMES;

typedef std::string UUID;

typedef std::string URL;

}}} // namespace

#endif
