// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "TokenService.h"
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace tw::maple::generated;

class TokenServiceHandler : virtual public TokenServiceIf {
 public:
  TokenServiceHandler() {
    // Your initialization goes here
  }

  void getToken(std::string& _return, const std::string& userId, const int32_t default_expire_time) {
    // Your implementation goes here
    printf("getToken\n");
  }

  void removeToken(const std::string& token) {
    // Your implementation goes here
    printf("removeToken\n");
  }

  void checkToken(const std::string& token) {
    // Your implementation goes here
    printf("checkToken\n");
  }

  void getURL(std::string& _return, const std::string& token, const std::string& itemKey) {
    // Your implementation goes here
    printf("getURL\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<TokenServiceHandler> handler(new TokenServiceHandler());
  shared_ptr<TProcessor> processor(new TokenServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

